name: path_finder_app
description: A Flutter application for finding the shortest path.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  dartz: ^0.10.1
  dio: ^5.1.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  intl: ^0.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.1.5
  mockito: ^5.4.0

flutter:
  uses-material-design: true